config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", shared: "users/shared", passwords: "users/passwords"}
  root 'contents#index'

  namespace :api, :path => '/' do
    namespace :v1 do
      resources :contents, only: [:index, :show] do
        member do 
          get 'subcontents'
          put 'like' => 'contents#like'
          put 'unlike' => 'contents#unlike'
        end
      end
      resources :sections, only: [:index, :show] do
        resources :contents, only: [:index]
      end
      resources :publishers, only: [:index] do
        resources :contents, only: [:index]
      end
    end
  end
  
  resources :users 

  resources :authors

  resources :publishers

  resources :sections do
    resources :contents
  end

  resources :contents do
    collection do
      get 'add' => 'contents#add'
      get 'test' => 'contents#test'
      get 'update_views' => 'contents#update_views'
    end

    member do
      patch 'publish' => 'contents#publish'
      patch 'revoke' => 'contents#revoke'
      patch 'contribute' => 'contents#contribute'
      patch 'approve' => 'contents#approve'
      patch 'focus' => 'contents#focus'
      patch 'unfocus' => 'contents#unfocus'
    end
    resources :article_body_images
    resources :photos

    resources :contents do
      collection do
        get 'add' => 'contents#add'
      end

      member do
        patch 'publish' => 'contents#publish'
        patch 'revoke' => 'contents#revoke'
      end
      resources :article_body_images
      resources :photos
    end
  end

  post 'article_body_image/delete' => 'article_body_images#destroy'

end

app/controllers/api/v1/contents_controller.rb
class Api::V1::ContentsController < ApplicationController
  protect_from_forgery with: :null_session
  include ContentsHelper

  def index
    host_url = request.protocol + request.host_with_port

    @response = Hash.new

    validate_id = Proc.new { |param_name,id,parent|
      if params.include?(param_name)
        if id.to_i.to_s != id
          @response["status"] = 1
          @response["message"] = "Invaild #{param_name}"
          render :json => @response, status: 400
          return
        elsif not parent.exists?(id)
          @response["status"] = 2
          @response["message"] = "#{param_name} didn't exist"
          render :json => @response, status: 404
          return
        else
          id
        end
      else
        nil
      end
    }

    check_parameter = Proc.new{ |name,value|  
      if params.include?(name) && (value.to_i.to_s != value) || value.to_i != value.to_f
        @response["status"] = 1
        @response["message"] = "Invaild parameter : #{name}"
        render :json => @response , status: 400
        return
      end
    }

    # v1/sections/:section_id/contents
    @section_id = validate_id.call('section_id',params[:section_id],Section,@section_id)

    # v1/publishers/:publisher_id/contents
    @publisher_id = validate_id.call('publisher_id',params[:publisher_id],Publisher)

    # v1/contents
    # if params.include?('on_focus') && params[:on_focus] == 'true' && !params.include?('publisher_id')
    #   @response["status"] = 0
    #   @response["message"] = "ok"
    #   @response["list"] = Content.get_focus(host_url)
    #   render :json => @response
    #   return
    # end

    if params.include?('content_type')
      case params[:content_type]
      when "article" then content_type = :article
      when "video" then content_type = :video
      when "album" then content_type = :album
      when "special" then content_type = :special
      else 
        @response["status"] = 3
        @response["message"] = "content_type not exist"
        render :json => @response
        return
      end
    else
      content_type = nil
    end

    check_parameter.call('limit',params[:limit])
    check_parameter.call('since_id',params[:since_id])
    check_parameter.call('max_id',params[:max_id])

    from_max = true
    if params.include?('limit')
      limit = params[:limit].to_i
      if limit > 76
        limit = 76
      end
    else
      limit = 10
    end
    if params.include?('since_id')
      since_id = params[:since_id].to_i
      from_max = false
    else
      since_id = 0
    end
    if params.include?('max_id')
      max_id = params[:max_id].to_i
      from_max = true
    else
      max_id = Content.where(delete_flag: false ,status: Content.statuses[:published]).last(1)[0].id
    end

    case params[:on_focus]
    when "true" then on_focus = true
    when "false" then on_focus = false
    else on_focus = false
    end

    case params[:on_timeline]
    when "true" then on_timeline = true
    when "false" then on_timeline = false
    else on_timeline = false
    end

    if @publisher_id != nil
      list = Content.get_contents_by_publisher(@publisher_id,limit,max_id,since_id,content_type,from_max,host_url)
    elsif @section_id != nil
      list = Content.get_contents_by_section(@section_id,limit,max_id,since_id,content_type,from_max,host_url)
    else
      list = Content.get_list(limit,max_id,since_id,on_focus,on_timeline,content_type,from_max,host_url)
    end
    @response["status"] = 0
    @response["message"] = 'ok'
    @response["list"] = list
    render :json => @response
  end

  def show
    host_url = request.protocol + request.host_with_port
    @response = Hash.new

    if not Content.exists?(params[:id])
      @response["status"] = 1
      @response["message"] = "content didn't exist"
      render :json => @response, status: 404
      return
    end

    @content = Content.find(params[:id])
    # fresh_when(@content)
    if @content.status != 'published'
      @response["status"] = 1
      @response["message"] = "content didn't exist"
      render :json => @response, status: 404
      return
    end
    if @content.delete_flag
      @response["status"] = 2 
      @response["message"] = "content had been deleted"
      render :json => @response, status: 404
      return
    end

    #record views
    @content.views += 1
    @content.template_html = update_html_info(@content.template_html,@content.views,@content.like)
    @content.save
    render :json => @content.get_detail(host_url)
  end

  def subcontents
    host_url = request.protocol + request.host_with_port
    @response = Hash.new

    if params[:id].to_i.to_s != params[:id]
      @response["status"] = 1
      @response["message"] = "Invaild id"
      render :json => @response, status: 400
    elsif Content.exists?(params[:id])
      @response["status"] = 0
      @response["message"] = "ok"
      @response["list"] = Content.get_subcontents(params[:id],host_url)
      render :json => @response
    else
      @response["status"] = 2
      @response["message"] = "content didn't exist"
      render :json => @response, status: 400
    end
    return
  end

  def like
    @response = Hash.new
    if params[:id].to_i.to_s != params[:id]
      @response["status"] = 1
      @response["message"] = "Invaild id"
      render :json => @response, status: 400
    elsif Content.exists?(params[:id])
      @content = Content.find(params[:id])
      @content.like += 1
      @response["status"] = 0
      @response["message"] = "ok"
      @response["like"] = @content.like
      @content.template_html = update_html_info(@content.template_html,@content.views,@content.like)
      @content.save
      render :json => @response
    else
      @response["status"] = 2
      @response["message"] = "content didn't exist"
      render :json => @response, status: 400
    end
  end

  def unlike
    @response = Hash.new
    if params[:id].to_i.to_s != params[:id]
      @response["status"] = 1
      @response["message"] = "Invaild id"
      render :json => @response, status: 400
    elsif Content.exists?(params[:id])
      @content = Content.find(params[:id])
      if @content.like > 0
        @content.like -= 1
      end
      @response["status"] = 0
      @response["message"] = "ok"
      @response["like"] = @content.like
      @content.template_html = update_html_info(@content.template_html,@content.views,@content.like)
      @content.save
      render :json => @response
    else
      @response["status"] = 2
      @response["message"] = "content didn't exist"
      render :json => @response, status: 400
    end
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
  require 'nokogiri'
  def status_label(content, label_text)
    if content.draft?
      "<span class='label label-default label-lg'>#{label_text}</span>"
    elsif content.published? || content.approved?
      "<span class='label label-success'>#{label_text}</span>"
    elsif content.pending?
      "<span class='label label-warning'>#{label_text}</span>"
    elsif content.rejected?
      "<span class='label label-danger'>#{label_text}</span>"
    end
  end

  def content_type_label(content, label_text)
    if content.article?
      "<span class='label label-info'><span class='glyphicon glyphicon-file'></span>    #{label_text}</span>"
    elsif content.album?
      "<span class='label label-danger'><span class='glyphicon glyphicon-picture'></span>    #{label_text}</span>"
    elsif content.video?
      "<span class='label label-warning'><span class='glyphicon glyphicon-facetime-video'>   </span>    #{label_text}</span>"
    elsif content.special?
      "<span class='label label-success'><span class='glyphicon glyphicon-star'>   </span>    #{label_text}</span>"
    end
  end

  def focus_label(content)
    if content.on_focus?
      "<span class='label label-warning'>" + t("focus") + "</span>"
    else
      ""
    end
  end

  def get_mobile_html(html_string)
    html_doc = Nokogiri::HTML(html_string)
    html_doc.css("img").each do |img|
      img["style"] = "width:100%"
    end
    return html_doc.to_html
  end

  def get_mobile_video_html(html_string)
    html_doc = Nokogiri::HTML(html_string)
    html_doc.css("img").each do |img|
      img["style"] = "width:100%"
    end
    html_doc.css("iframe").each do |iframe|
      iframe["width"] = "100%"
      iframe["style"] = "height:9rem;margin-top:0.714rem"
    end
    return html_doc.to_html
  end

  def get_video_id(url)
    if url =~ URI::regexp
      begin
        uri = URI.parse(url)
      rescue URI::InvalidURIError => e
        return ""
      end
      return /\/id_(.*)\.html/.match(uri.path)[1]
    else
      return ""
    end
  end

  def update_html_info(html_string,views,like)
    html_doc = Nokogiri::HTML(html_string)
    html_doc.css("#views").each do |each|
      each.inner_html = "有#{views}个路人来过"
    end
    html_doc.css("#like").each do |each|
      each.inner_html = "收到#{like}个赞"
    end
    return html_doc.to_html
  end
end

app/views/contents/_base_form.html.erb
<%= form_for @content, :html => { :multipart => true } do |f| %>
    <% if @content.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@time_line_item.errors.count, "error") %>
            prohibited
            this article from being saved:</h2>
          <ul>
            <% @content.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :subtitle %>
      <%= f.text_field :subtitle %>
    </p>

    <p>
      <%= f.label :description %>
      <%= f.text_field :description %>
    </p>

    <p>
      <%= f.label :status %>
      <%= f.select :status, options_for_select(Content.statuses.keys.to_a, selected: @content.status) %>
    </p>

    <p>
      <%= f.label :content_type %>
      <%= f.select :content_type, options_for_select(Content.content_types.keys.to_a, selected: @content.content_type) %>
    </p>

    <p>
      <%= f.label :author_id %>
      <%= f.select :author_id, options_for_select(author_selection_field_dict, selected: @content.author_id) %>
    </p>

    <p>
      <%= f.label :section_id %>
      <%= f.select :section_id, options_for_select(section_selection_field_dict, selected: @content.section_id) %>
    </p>

    <p>
      <%= f.label :header_image %>
      <%= f.file_field :header_image %>
    </p>

    <p>
      <%= f.label :header_image_info %>
      <%= f.text_field :header_image_info %>
    </p>

    <p>
      <%= f.submit class: 'content_submit_button'%>
    </p>
<% end %>

app/views/contents/_list.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= t :header_img %></th>
    <th><%= t :type %></th>
    <th><%= t :title %></th>
    <th><%= t :subtitle %></th>
    <th><%= t :description %></th>
    <th><%= t :status %></th>


  </tr>
  </thead>

  <tbody>
  <% contents.each do |content| %>
      <tr>
        <td><%= image_tag content.header_image.url(:thumb) %></td>
        <td><%=raw content_type_label(content, t(content.content_type)) %></td>
        <td><%= content.title %></td>
        <td><%= content.subtitle %></td>
        <td><%= content.description %></td>
        <td><%=raw status_label(content, t(content.status)) %></td>


        <td><%= link_to t('show'), content_path(content),
              {role: 'button', class: 'btn btn-info'}%>
            <%= link_to t('edit'), edit_content_path(content),
              {role: 'button', class: 'btn btn-warning'}%></td>
      </tr>
  <% end  %>
  </tbody>
</table>

app/views/contents/index.html.erb
<div class="jumbotron">
  <h1>Hello~</h1>
</div>

<div class="page-header">
  <% if current_user.have_authority('manage') %>
    <h3><%= t :manage %></h3>
      <%= link_to sections_path, {role: 'button', class: 'btn btn-primary'} do %>
        <%= t :manage_sections %>
      <% end %>
      <%= link_to publishers_path, {role: 'button', class: 'btn btn-primary'} do %>
        <%= t :manage_publishers %>
      <% end %>
      <% if current_user.super_admin? %>
        <%= link_to users_path, {role: 'button', class: 'btn btn-primary'} do %>
          <%= t :manage_users %>
        <% end %>
      <% end %>
  <% end %>
  <h3><%= t :all_contents %></h3>
    <%= link_to add_contents_path(content_type: :article), {role: 'button', class: 'btn btn-primary'} do %>
      <span class='glyphicon glyphicon-file'></span> <%= t :add_article %>
    <% end %>
    <%= link_to add_contents_path(content_type: :album), {role: 'button', class: 'btn btn-primary'} do %>
      <span class='glyphicon glyphicon-picture'></span> <%= t :add_album %>
    <% end %>
    <%= link_to add_contents_path(content_type: :video), {role: 'button', class: 'btn btn-primary'} do %>
      <span class='glyphicon glyphicon-facetime-video'></span> <%= t :add_video %>
    <% end %>
    <% if current_user.have_authority('access_specials') %>
      <%= link_to add_contents_path(content_type: :special), {role: 'button', class: 'btn btn-primary'} do %>
        <span class='glyphicon glyphicon-star'></span> <%= t :add_special%>
      <% end %>
    <% end %>
</div>


<div class="row">
  <div class="col-md-12">
    <ul id="tabs" class="nav nav-tabs" role="tablist">
      <li id='all_tab'><a href="/#tabs"><%= t :all %></a></li>
      <li id='article_tab'><a href="?content_type=article#tabs"><%= t :article %></a></li>
      <li id='video_tab'><a href="?content_type=video#tabs"><%= t :video %></a></li>
      <li id='album_tab'><a href="?content_type=album#tabs"><%= t :album %></a></li>
      <li id='special_tab'><a href="?content_type=special#tabs"><%= t :special %></a></li>
      <li id='contributions_tab'><a href="?contributions=true#tabs"><%= t :contributions %></a></li>
    </ul>
    <table class="table table-striped">
      <thead>
      <tr>
        <th class="col-md-1"><%= t :header_img %></th>
        <th class="col-md-1"><%= t :type %></th>
        <th class="col-md-2"><%= t :title %></th>
        <th class="col-md-2"><%= t :subtitle %></th>
        <th class="col-md-3"><%= t :description %></th>
        <th class="col-md-1"><%= t :status %></th>
        <th class="col-md-2"></th>
      </tr>
      </thead>

      <tbody>
      <% @contents.each do |content| %>
          <tr>
            <td class="col-md-1"><%= image_tag(content.header_image.url(:thumb), height: '100') %></td>
            <td class="col-md-1"><%=raw content_type_label(content,t(content.content_type)) %></td>
            <td class="col-md-2"><%= content.title %></td>
            <td class="col-md-2"><%= content.subtitle %></td>
            <td class="col-md-3"><%= content.description %></td>
            <td class="col-md-1"><%=raw status_label(content, t(content.status)) %></br>
                <%=raw focus_label(content) %></td>


            <td class="col-md-2"><%= link_to t('show'), content_path(content),
                {role: 'button', class: 'btn btn-info'}%>
            <% if current_user.can_modify_content(content.id) %>
                <%= link_to t('edit'), edit_content_path(content),
                  {role: 'button', class: 'btn btn-warning'}%>
            <% end %>
            </td>
          </tr>
      <% end  %>
      </tbody>
    </table>
    <%= paginate @contents, :reomte => true %>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
    var type = getUrlParameter('content_type');
    var contributions = getUrlParameter('contributions')
    if(type == "article")
    {
      $("#article_tab").addClass("active")
    }
    else if(type == "album")
    {
      $("#album_tab").addClass("active")
    }
    else if(type == "video")
    {
      $("#video_tab").addClass("active")
    }
    else if(contributions == "true")
    {
      $("#contributions_tab").addClass("active")
    }

    if(type == undefined && contributions == undefined)
    {
      $("#all_tab").addClass("active")
    }

    function getUrlParameter(sParam)
    {
      var sPageURL = window.location.search.substring(1);
      var sURLVariables = sPageURL.split('&');
      for (var i = 0; i < sURLVariables.length; i++) 
      {
          var sParameterName = sURLVariables[i].split('=');
          if (sParameterName[0] == sParam) 
          {
              return sParameterName[1];
          }
      }
    }
</script>

app/views/contents/new.html.erb
<h1> new Content </h1>
<%= render 'base_form' %>
<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<div class="page-header">
  <% if @content.parent_content_id == 0%>
      <%= link_to t('back'), contents_path, 
    {role: 'button', class: 'btn btn-default'}%>
  <% else %>
      <%= link_to t('back'), content_path(@content.parent_content_id), 
    {role: 'button', class: 'btn btn-default'}%>
  <% end %>
</div>

<div class="row">
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= t :content_meta_data %>
        <%=raw status_label(@content,t(@content.status)) %>
        <%=raw content_type_label(@content, t(@content.content_type)) %>
        <%=raw focus_label(@content) %>
        <% if current_user.admin? or current_user.super_admin? %>
          <span class='label label-primary'><%= t('views') + ":" + @content.views.to_s %></span>
          <span class='label label-danger'><%= t('like') + ":" + @content.like.to_s %></span>
        <% end %>
      </div>
      <div class="panel-body">
        <p>
          <strong>id: </strong>
          <%= @content.id %>
        </p>
        <p>
          <strong> <%= t :title %>: </strong>
          <%= @content.title %>
        <p>
          <strong> <%= t :subtitle %>: </strong>
          <%= @content.subtitle %>
        </p>
        <p>
          <strong> <%= t :description %>: </strong><br/>
          <%= @content.description %>
        </p>

        <p>
          <strong> <%= t :header_img %>: </strong><br/>
          <%= image_tag @content.header_image.url(:thumb) %>
        </p>
      </div>
    </div>
    <% case  @content.content_type %>
    <% when 'article' %>
        <hr>
        <div>
          <%=raw @content.body_html %>
        </div>
    <% when 'album'%>
        <strong> <%= t :photos %>:</strong>
        <ul class="media-list">
          <%= render @content.photos %>
        </ul>

    <% when 'video'%>
        <div class="row">
          <div class="col-sm-12">
            <div class="panel panel-default">
              <div class="panel-heading"><%= t :video %>Url</div>
              <div class="panel-body">
                <%= @content.video_url %>
              </div>
            </div>
          </div>
        </div>
    <% end %>

  </div>
  <div class="col-md-4">
    <!-- Action panel-->
    <div class="panel panel-primary">
      <div class="panel-heading">
        <%= t :actions %>
      </div>
      <div class="panel-body">
        <% if current_user.have_authority('publish') %>
          <% if @content.draft? %>
              <%= link_to t('publish'), publish_content_path(@content), method: :patch, data: {confirm: t('are_you_sure_to_publish')}, role: 'button', class: 'btn btn-success' %>
              <%= link_to t('edit'), edit_content_path(@content), {role: 'button', class: 'btn btn-default'}%>
          <% elsif @content.pending? %>
              <%= link_to t('approve'), approve_content_path(@content), method: :patch, data: {confirm: t('are_you_sure_to_approve')}, role: 'button', class: 'btn btn-success' %>
          <% else %>
              <% if @content.parent_content_id == 0 %>
                <% if @content.on_focus? %>
                    <%= link_to t('unset_focus'), unfocus_content_path(@content), method: :patch, role: 'button', class: 'btn btn-info' %>
                <% else %>
                    <%= link_to t('set_focus'), focus_content_path(@content), method: :patch, role: 'button', class: 'btn btn-warning' %>
                <% end %>
              <% end %>
              <%= link_to t('revoke'), revoke_content_path(@content), method: :patch, data: {confirm: t('are_you_sure_to_revoke')}, role: 'button', class: 'btn btn-default' %>
          <% end %>
        <% else %>
          <% if @content.draft? || @content.rejected? %>
              <%= link_to t('contribute'), contribute_content_path(@content), method: :patch, data: {confirm: t('are_you_sure_to_contribute')}, role: 'button', class: 'btn btn-success' %>
              <%= link_to t('edit'), edit_content_path(@content), {role: 'button', class: 'btn btn-default'}%>
          <% elsif not @content.approved? %>
                <%= link_to t('revoke'), revoke_content_path(@content), method: :patch, data: {confirm: t('are_you_sure_to_revoke_contribution')}, role: 'button', class: 'btn btn-default' %>
          <% end %>
        <% end %>
        <!-- Single button -->
        <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            <%= t :other_action %> <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to t('delete'), content_path(@content),
             method: :delete, data: { confirm: t('are_you_sure')},
             role: 'button', class: 'btn btn-danger' %>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <!-- Action panel END -->

    <!-- Publisher panel -->
    <div class="panel panel-default">
      <div class="panel-heading"><%= t :publisher %></div>
      <div class="panel-body">
        <strong><%= t :name %>:</strong>
        <%= @content.publisher.name %>
      </div>
    </div>
    <!--Publisher panel END-->

    <!-- Author panel -->
    <div class="panel panel-default">
      <div class="panel-heading"><%= t :author %></div>
      <div class="panel-body">
        <strong><%= t :display_name %>:</strong>
        <%= @content.user.display_name %>
        <br/>
      </div>
    </div>
    <!--Author panel END-->

    <!--Section panel -->
    <div class="panel panel-default">
      <div class="panel-heading"><%= t :section %></div>
      <div class="panel-body">
        <strong><%= t :category %>:</strong>
        <%= t(@content.section.category) %>
        <br/>
        <strong><%= t :module %>:</strong>
        <%= @content.section.module %>
      </div>
    </div>
    <!-- Section panel END-->
  </div>
</div>

app/views/contents/show_special.html.erb
<div class="page-header">
    <%= link_to t('back'), contents_path, 
  {role: 'button', class: 'btn btn-default'}%>
</div>

<div class="row">
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= t :content_meta_data %>
        <%=raw status_label(@content, t(@content.status)) %>
        <%=raw content_type_label(@content, t(@content.content_type)) %>
        <%=raw focus_label(@content) %>
        <% if current_user.admin? or current_user.super_admin? %>
          <span class='label label-primary'><%= t('views') + ":" + @content.views.to_s %></span>
          <span class='label label-danger'><%= t('like') + ":" + @content.like.to_s %></span>
        <% end %>
      </div>
      <div class="panel-body">
        <p>
          <strong>id: </strong>
          <%= @content.id %>
        </p>
        <p>
          <strong> <%= t :title %>: </strong>
          <%= @content.title %>
        <p>
          <strong> <%= t :subtitle %>: </strong>
          <%= @content.subtitle %>
        </p>
        <p>
          <strong> <%= t :description %>: </strong><br/>
          <%= @content.description %>
        </p>

        <p>
          <strong> <%= t :header_img %>:</strong><br/>
          <%= image_tag @content.header_image.url(:thumb) %>
        </p>
      </div>
    </div>
    <hr/>
    <%= render partial: 'list' , locals: {contents: @content.subcontents}%>

  </div>

  <div class="col-md-4">
    <!-- Action panel-->
    <div class="panel panel-primary">
      <div class="panel-heading">
        <%= t :actions %>
      </div>
      <div class="panel-body">
      <% if current_user.have_authority('publish') %>
        <% if @content.draft? %>
            <%= link_to t('publish'), publish_content_path(@content), method: :patch, data: {confirm: 'Are you sure to publish this content?'}, role: 'button', class: 'btn btn-success' %>
            <%= link_to t('edit'), edit_content_path(@content), {role: 'button', class: 'btn btn-default'}%>
        <% elsif @content.pending? %>
            <%= link_to t('approve'), approve_content_path(@content), method: :patch, data: {confirm: 'Are you sure to approve this content?'}, role: 'button', class: 'btn btn-success' %>
        <% else %>
            <% if @content.on_focus? %>
              <%= link_to t('unset_focus'), unfocus_content_path(@content), method: :patch, role: 'button', class: 'btn btn-info' %>
            <% else %>
              <%= link_to t('set_focus'), focus_content_path(@content), method: :patch, role: 'button', class: 'btn btn-warning' %>
            <% end %>
            <%= link_to t('revoke'), revoke_content_path(@content), method: :patch, data: {confirm: 'Are you sure to revoke this content?'}, role: 'button', class: 'btn btn-default' %>
        <% end %>
      <% else %>
        <% if @content.draft? || @content.rejected? %>
            <%= link_to t('contribute'), contribute_content_path(@content), method: :patch, data: {confirm: 'Are you sure to contribute this content?'}, role: 'button', class: 'btn btn-success' %>
            <%= link_to t('edit'), edit_content_path(@content), {role: 'button', class: 'btn btn-default'}%>
        <% elsif not @content.approved? %>
              <%= link_to t('revoke'), revoke_content_path(@content), method: :patch, data: {confirm: 'Are you sure to revoke this content?'}, role: 'button', class: 'btn btn-default' %>
        <% end %>
      <% end %>
        <!-- Single button -->
        <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            <%= t :other_action %> <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to t('delete'), content_path(@content),
                            method: :delete, data: { confirm: 'Are you sure?'},
                            role: 'button', class: 'btn btn-danger' %>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <!-- Action panel END -->

    <!--Publisher panel -->
    <div class="panel panel-default">
      <div class="panel-heading"><%= t :publisher %></div>
      <div class="panel-body">
        <strong><%= t :name %>:</strong>
        <%= @content.publisher.name %>
      </div>
    </div>
    <!-- Publisher panel END-->

    <!--Section panel -->
    <div class="panel panel-default">
      <div class="panel-heading"><%= t :section %></div>
      <div class="panel-body">
        <strong><%= t :category %>:</strong>
        <%= @content.section.category %>
        <br/>
        <strong><%= t :module %>:</strong>
        <%= @content.section.module %>
      </div>
    </div>
    <!-- Section panel END-->

    <!-- Author panel -->
    <div class="panel panel-default">
      <div class="panel-heading"><%= t :author %></div>
      <div class="panel-body">
        <strong><%= t :display_name %>:</strong>
        <%= @content.user.display_name  %>
      </div>
    </div>
    <!--Author panel END-->
  </div>
</div>