config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", shared: "users/shared", passwords: "users/passwords"}
  root 'contents#index'

  namespace :api, :path => '/' do
    namespace :v1 do
      resources :contents, only: [:index, :show] do
        member do 
          get 'subcontents'
          put 'like' => 'contents#like'
          put 'unlike' => 'contents#unlike'
        end
      end
      resources :sections, only: [:index, :show] do
        resources :contents, only: [:index]
      end
      resources :publishers, only: [:index] do
        resources :contents, only: [:index]
      end
    end
  end
  
  resources :users 

  resources :authors

  resources :publishers

  resources :sections do
    resources :contents
  end

  resources :contents do
    collection do
      get 'add' => 'contents#add'
      get 'test' => 'contents#test'
      get 'update_views' => 'contents#update_views'
    end

    member do
      patch 'publish' => 'contents#publish'
      patch 'revoke' => 'contents#revoke'
      patch 'contribute' => 'contents#contribute'
      patch 'approve' => 'contents#approve'
      patch 'focus' => 'contents#focus'
      patch 'unfocus' => 'contents#unfocus'
    end
    resources :article_body_images
    resources :photos

    resources :contents do
      collection do
        get 'add' => 'contents#add'
      end

      member do
        patch 'publish' => 'contents#publish'
        patch 'revoke' => 'contents#revoke'
      end
      resources :article_body_images
      resources :photos
    end
  end

  post 'article_body_image/delete' => 'article_body_images#destroy'

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :contents

  enum department: [:admin_dept, :hr_dept, :news_dept,
                    :channel_dept, :video_dept, :market_dept,
                    :image_dept, :tech_dept, :design_dept, :pm_dept]
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def defalut_author

  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to @author
    else
      render 'new'
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])

    if @author.update(author_params)
      redirect_to @author
    else
      render 'edit'
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    redirect_to authors_path
  end

  private
  def author_params
    params.require(:author).permit(:department, :name, :display_name)
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
  def author_selection_field_dict
    authors = Author.all
    dict = {}
    authors.each do |author|
      dict["#{author.name}-#{author.display_name}"] = author.id if author.active
    end

    dict
  end
end

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>

    <% if @author.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@author.errors.count, "error") %>
            prohibited
            this article from being saved:</h2>
          <ul>
            <% @author.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :department %>
      <%= f.select :department, options_for_select(Author.departments.keys.to_a, selected: @author.department) %>
    </p>

    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :display_name %>
      <%= f.text_field :display_name %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/authors/edit.html.erb
<h1> edit author </h1>

<%= render 'form' %>

<%= link_to 'Back', author_path(@author) %>

app/views/authors/index.html.erb
<h1> all authors </h1>

<table>
  <tr>
    <th>id</th>
    <th>Department</th>
    <th>Name</th>
    <th>Display Name</th>
  </tr>

  <% @authors.each do |author| %>
      <tr>
        <td><%= author.id %></td>
        <td><%= author.department %></td>
        <td><%= author.name %></td>
        <td><%= author.display_name %></td>

        <td><%= link_to 'Show', author_path(author) %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Delete', author_path(author),
                        method: :delete, data: { confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  <%= link_to 'new author', new_author_path %>
</table>

app/views/authors/new.html.erb
<h1> new author </h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<h1> Author </h1>

<p>
  <strong>id: </strong>
  <%= @author.id %>
</p>

<p>
  <strong> Name: </strong>
  <%= @author.name %>

<p>
  <strong> Department: </strong>
  <%= @author.department %>
</p>

<p>
  <strong> Display name: </strong>
  <%= @author.display_name %>
</p>

<%= link_to 'Back', authors_path %>
<%= link_to 'Edit', edit_author_path(@author) %>