config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", shared: "users/shared", passwords: "users/passwords"}
  root 'contents#index'

  namespace :api, :path => '/' do
    namespace :v1 do
      resources :contents, only: [:index, :show] do
        member do 
          get 'subcontents'
          put 'like' => 'contents#like'
          put 'unlike' => 'contents#unlike'
        end
      end
      resources :sections, only: [:index, :show] do
        resources :contents, only: [:index]
      end
      resources :publishers, only: [:index] do
        resources :contents, only: [:index]
      end
    end
  end
  
  resources :users 

  resources :authors

  resources :publishers

  resources :sections do
    resources :contents
  end

  resources :contents do
    collection do
      get 'add' => 'contents#add'
      get 'test' => 'contents#test'
      get 'update_views' => 'contents#update_views'
    end

    member do
      patch 'publish' => 'contents#publish'
      patch 'revoke' => 'contents#revoke'
      patch 'contribute' => 'contents#contribute'
      patch 'approve' => 'contents#approve'
      patch 'focus' => 'contents#focus'
      patch 'unfocus' => 'contents#unfocus'
    end
    resources :article_body_images
    resources :photos

    resources :contents do
      collection do
        get 'add' => 'contents#add'
      end

      member do
        patch 'publish' => 'contents#publish'
        patch 'revoke' => 'contents#revoke'
      end
      resources :article_body_images
      resources :photos
    end
  end

  post 'article_body_image/delete' => 'article_body_images#destroy'

end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :contents
  has_many :users
end

app/controllers/api/v1/publishers_controller.rb
class Api::V1::PublishersController < ApplicationController
  def index
    @response = Hash.new
    @response["status"] = 0
    @response["message"] = 1
    @response["Publishers"] = Publisher.all
    render :json => @response
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_group

  def index
    @publishers = Publisher.where.not(id: 0)
  end

  def show
    @publisher = Publisher.find(params[:id])
  end

  def new
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)

    if @publisher.save
      redirect_to @publisher
    else
      render 'new'
    end
  end

  def edit
    @publisher = Publisher.find(params[:id])
  end

  def update
    @publisher = Publisher.find(params[:id])

    if @publisher.update(publisher_params)
      redirect_to @publisher
    else
      render 'edit'
    end
  end

  def destroy
    @publisher = Publisher.find(params[:id])
    @publisher.destroy

    redirect_to publishers_path
  end

  private
  def publisher_params
    params.require(:publisher).permit(:name)
  end

  def check_group
    if not current_user.have_authority('access_publishers')
      #have no right to access publishers
      redirect_to contents_path
    end
  end
end

app/views/publishers/_form.html.erb
<%= form_for @publisher do |f| %>

    <% if @publisher.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@publisher.errors.count, "error") %>
            prohibited
            this article from being saved:</h2>
          <ul>
            <% @publisher.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label t :name %>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/publishers/edit.html.erb
<h1><%= t :edit %><%= t :publisher %></h1>

<%= render 'form' %>

<%= link_to t('back'), publishers_path, 
	{role: 'button', class: 'btn btn-default'}%>

app/views/publishers/index.html.erb
<h1><%= t :manage_publishers %></h1>
<%= link_to new_publisher_path, {role: 'button', class: 'btn btn-primary'} do%>
  <span class="glyphicon glyphicon-plus"></span> <%= t :new_publisher %>
<% end %>
&nbsp
<%= link_to t("back"), contents_path ,{role: 'button', class: 'btn btn-default'}%>

<table class="table table-striped">
  <thead>
  <tr>
    <th>id</th>
    <th><%= t :name %></th>
  </tr>
  </thead>
  <tbody>
    <% @publishers.each do |publisher| %>
        <tr>
          <td><%= publisher.id %></td>
          <td><%= publisher.name %></td>

          <td><%= link_to t('show'), publisher_path(publisher), {role: 'button', class: 'btn btn-info'}%>
          <%= link_to t('edit'), edit_publisher_path(publisher), {role: 'button', class: 'btn btn-warning'}%>
          <%= link_to t('delete'), publisher_path(publisher),
                        method: :delete, data: { confirm: t("are_you_sure")},
                        role: 'button', class: 'btn btn-danger' %></td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/publishers/new.html.erb
<h1> new publisher </h1>

<%= render 'form' %>

<%= link_to 'Back', publishers_path %>

app/views/publishers/show.html.erb
<h1> <%= t :publisher %> </h1>

<p>
  <strong>id: </strong>
  <%= @publisher.id %>
</p>

<p>
  <strong> <%= t :name %>: </strong>
  <%= @publisher.name %>
</p>

<%= link_to t('back'), publishers_path,
	{role: 'button', class: 'btn btn-default'}%>
<%= link_to t('edit'), edit_publisher_path(@publisher),
	{role: 'button', class: 'btn btn-warning'}%>