config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", shared: "users/shared", passwords: "users/passwords"}
  root 'contents#index'

  namespace :api, :path => '/' do
    namespace :v1 do
      resources :contents, only: [:index, :show] do
        member do 
          get 'subcontents'
          put 'like' => 'contents#like'
          put 'unlike' => 'contents#unlike'
        end
      end
      resources :sections, only: [:index, :show] do
        resources :contents, only: [:index]
      end
      resources :publishers, only: [:index] do
        resources :contents, only: [:index]
      end
    end
  end
  
  resources :users 

  resources :authors

  resources :publishers

  resources :sections do
    resources :contents
  end

  resources :contents do
    collection do
      get 'add' => 'contents#add'
      get 'test' => 'contents#test'
      get 'update_views' => 'contents#update_views'
    end

    member do
      patch 'publish' => 'contents#publish'
      patch 'revoke' => 'contents#revoke'
      patch 'contribute' => 'contents#contribute'
      patch 'approve' => 'contents#approve'
      patch 'focus' => 'contents#focus'
      patch 'unfocus' => 'contents#unfocus'
    end
    resources :article_body_images
    resources :photos

    resources :contents do
      collection do
        get 'add' => 'contents#add'
      end

      member do
        patch 'publish' => 'contents#publish'
        patch 'revoke' => 'contents#revoke'
      end
      resources :article_body_images
      resources :photos
    end
  end

  post 'article_body_image/delete' => 'article_body_images#destroy'

end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :contents

  enum category: [:news, :special, :weekly, :video]

  has_attached_file :section_image, :styles => { :medium => "300x300>"}, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :section_image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/api/v1/sections_controller.rb
class Api::V1::SectionsController < ApplicationController
  def index
    @response = Hash.new
    @response["status"] = 0
    @response["message"] = 1
    @response["sections"] = Section.all
    render :json => @response
  end

  def show
    @response = Hash.new
    if(params[:id].to_i.to_s == params[:id] && params[:id].to_f == params[:id].to_i)
      if(!Section.exists?(params[:id]))
        @response["status"] = 2
        @response["message"] = "section didn't exists"
        render :json => @response, status: 404
        return
      end
    else
      @response["status"] = 1
      @response["message"] = "Invalid id"
      render :json => @response, status: 400
      return
    end
    @response["status"] = 0
    @response["message"] = 'ok'
    @response["section"] = Section.find(params[:id])
    render :json => @response 
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_group

  def index
    @sections = Section.all
  end

  def show
    @section = Section.find(params[:id])
  end

  def new
    @section = Section.new
  end

  def create
    @section = Section.new(section_params)

    if @section.save
      redirect_to @section
    else
      render 'new'
    end
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])

    if @section.update(section_params)
      redirect_to @section
    else
      render 'edit'
    end
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy

    redirect_to sections_path
  end

  private
  def section_params
    params.require(:section).permit(:category, :module)
  end

  def check_group
    if not current_user.have_authority('access_sections')
      #have no right to access sections
      redirect_to contents_path
    end
  end
end

app/helpers/sections_helper.rb
module SectionsHelper
  def section_selection_field_dict
    sections = Section.all
    dict = {}
    sections.each do |section|
      dict["#{section.category}-#{section.module}"] = section.id if section.active
    end

    dict
  end
end

app/views/sections/_form.html.erb
<%= form_for @section do |f| %>

    <% if @section.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@section.errors.count, "error") %>
            prohibited
            this article from being saved:</h2>
          <ul>
            <% @section.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label t :category %>
      <%= f.select :category, options_for_select({ t("news") => "news",t("special") => "special", t("weekly") => "weekly", t("video") => "video" }, selected: @section.category) %>
    </p>

    <p>
      <%= f.label t :module %>
      <%= f.text_field :module %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/sections/edit.html.erb
<h1> <%= t :edit %><%= t :section %></h1>

<%= render 'form' %>

<%= link_to t('back'), sections_path, {role: 'button', class: 'btn btn-default'}%>

app/views/sections/index.html.erb
<h1> <%= t :manage_sections %> </h1>
<%= link_to new_section_path, {role: 'button', class: 'btn btn-primary'} do %>
  <span class="glyphicon glyphicon-plus"></span> <%= t :new_section %>
<% end %>
&nbsp
<%= link_to t("back"), contents_path ,{role: 'button', class: 'btn btn-default'}%>

<table class="table table-striped">
  <thead>
    <tr>
      <th>id</th>
      <th><%= t :category %></th>
      <th><%= t :module %></th>
    </tr>
  </thead>
  <tbody>
    <% @sections.each do |section| %>
        <tr>
          <td><%= section.id %></td>
          <td><%= t section.category %></td>
          <td><%= section.module %></td>

          <td><%= link_to t('show'), section_path(section), 
                {role: 'button', class: 'btn btn-info'}%>
              <%= link_to t('edit'), edit_section_path(section), 
                {role: 'button', class: 'btn btn-warning'} %>
              <%= link_to t('delete'), section_path(section),
                        method: :delete, data: { confirm: t("are_you_sure")},
                        role: 'button', class: 'btn btn-danger' %></td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/sections/new.html.erb
<h1> new section </h1>

<%= render 'form' %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<h1><%= t :section %></h1>

<p>
  <strong>id: </strong>
  <%= @section.id %>
</p>

<p>
  <strong> <%= t :category %>: </strong>
  <%= t(@section.category) %>

<p>
  <strong> <%= t :module %>: </strong>
  <%= @section.module %>
</p>

<%= link_to t('back'), sections_path, {role: 'button', class: 'btn btn-default'}%>
<%= link_to t('edit'), edit_section_path(@section),
	{role: 'button', class: 'btn btn-warning'} %>